### ISSUE TITLE
message queue can grow arbitrarily large when SAS is unavailable

### ISSUE THREAD

**Issue by dimbleby** [Metaswitch/sasclient.py#1]
Looking over some old code when I spotted this bug.  This is only from code-reading so it's possible that I'm just wrong in some way.

However: it looks to me as though `Client.send()` will cause messages to be queued regardless of state, and the `MessageSender` only removes messages from the queue if it is connected to SAS.

So if SAS is unavailable I don't see what stops this queue from growing arbitrarily large, as the client tries and fails to send messages.

Probably ought to arrange that messages are simply discarded if SAS is unavailable when they are sent, and also that we empty the queue when SAS becomes unavailable.

I'm not aware of any project other than `heftie` using this library, and `heftie` is currently inactive.  So I don't propose to do anything about this - just raising the issue so that it doesn't get lost.

**Comment by benritchie** [comment]
adding myself as interested party

**Comment by huws** [comment]
Fixed under #12.  Now we have a finite queue length, which can be set by the client.  This prevents unbounded memory growth.
