### ISSUE TITLE
 'maximum recursion depth' error always seen the first time running make commands

### ISSUE THREAD

**Issue by jack-atack** [Metaswitch/sasclient.py#4]
When running several of the make commands (`make env`, and `make test` for example), we see a huge stack trace printed out (which I won't copy and paste), with the below error message:

```
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

To repro this, run `make clean`, followed by `make env`, on a checkout of this repository.  

This always appears the first time a make command is run, although is not seen on subsequent retries.  I have built debian packages integrating this library successfully, and they seem to function perfectly fine, so this isn't a blocking issue.  However, it feels really wrong that anyone doing development will hit this error constantly.

**Comment by rowenasmithlamkin** [comment]
Can you add some details of the setup you were running with? When I run this on my ubuntu VM the make commands all complete without errors.

**Comment by dimbleby** [comment]
cf pypa/setuptools#946

> Setuptools 34 specifically drops support for upgrading itself. I wouldn't expect easy_install -U setuptools to work...

I expect you can fix by changing the makefile to go `pip install --upgrade "setuptools>0.7"` instead of `easy_install -U "setuptools>0.7"`

**Comment by jack-atack** [comment]
That seems to have done the trick on my box!

**Comment by rowenasmithlamkin** [comment]
@jack-atack If you already have the fix available can you send me a pull request for it? Not much point in someone else going and making the change too!

**Comment by richardwhiuk** [comment]
I think @jack-atack has fixed this in https://github.com/Metaswitch/sasclient.py/pull/5
